import { Router } from "express";
import { adminRouter } from "./modules/admin/admin.routes.js";
import { aiKeysRouter } from "./modules/ai-keys/ai-keys.routes.js";
import { aiRunsRouter } from "./modules/ai-runs/ai-runs.routes.js";
import { atsRouter } from "./modules/ats/ats.routes.js";
import { analyticsRouter } from "./modules/analytics/analytics.routes.js";
import { billingRouter } from "./modules/billing/billing.routes.js";
import { promoCodesRouter } from "./modules/promo-codes/promo-codes.routes.js";
import { customTemplatesRouter } from "./modules/custom-templates/custom-templates.routes.js";
import { coverageRouter } from "./modules/coverage/coverage.routes.js";
import { importsRouter } from "./modules/imports/imports.routes.js";
import { jobsRouter } from "./modules/jobs/jobs.routes.js";
import { pdfsRouter } from "./modules/pdfs/pdfs.routes.js";
import { profilesRouter } from "./modules/profiles/profiles.routes.js";
import { publicRouter } from "./modules/public/public.routes.js";
import { resumesRouter } from "./modules/resumes/resumes.routes.js";
import { shareLinksRouter } from "./modules/share-links/share-links.routes.js";
import { suggestionsRouter } from "./modules/suggestions/suggestions.routes.js";
import { templatesRouter } from "./modules/templates/templates.routes.js";
import { uploadsRouter } from "./modules/uploads/uploads.routes.js";
import { usageRouter } from "./modules/usage/usage.routes.js";
import { usersRouter } from "./modules/users/users.routes.js";

export const v1 = Router();

v1.use(usersRouter);
v1.use(aiKeysRouter);
v1.use(aiRunsRouter);
v1.use(profilesRouter);
v1.use(templatesRouter);
v1.use(customTemplatesRouter);
v1.use(resumesRouter);
v1.use(pdfsRouter);
v1.use(uploadsRouter);
v1.use(importsRouter);
v1.use(jobsRouter);
v1.use(suggestionsRouter);
v1.use(coverageRouter);
v1.use(atsRouter);
v1.use(shareLinksRouter);
v1.use(analyticsRouter);
v1.use(publicRouter);
v1.use(usageRouter);
v1.use(billingRouter);
v1.use(promoCodesRouter);
v1.use(adminRouter);
