/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UsernameIndexRouteImport } from './routes/$username/index'
import { Route as UsernameSlugRouteImport } from './routes/$username/$slug'
import { Route as AppAdminRouteRouteImport } from './routes/_app/admin/route'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAtsRouteImport } from './routes/_app/ats'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppJobsRouteImport } from './routes/_app/jobs'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppWorkspaceRouteImport } from './routes/_app/workspace'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteAtsCheckerRouteImport } from './routes/_site/ats-checker'
import { Route as SiteDocsRouteRouteImport } from './routes/_site/docs/route'
import { Route as SitePricingRouteImport } from './routes/_site/pricing'
import { Route as SitePrivacyRouteImport } from './routes/_site/privacy'
import { Route as SiteTemplatesRouteImport } from './routes/_site/templates'
import { Route as SiteTermsRouteImport } from './routes/_site/terms'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminAiRouteImport } from './routes/_app/admin/ai'
import { Route as AppAdminContentRouteImport } from './routes/_app/admin/content'
import { Route as AppAdminRevenueRouteImport } from './routes/_app/admin/revenue'
import { Route as AppAdminSystemRouteImport } from './routes/_app/admin/system'
import { Route as AppAdminTrafficRouteImport } from './routes/_app/admin/traffic'
import { Route as AppMyTemplatesIndexRouteImport } from './routes/_app/my-templates/index'
import { Route as AppMyTemplatesCustomTemplateIdRouteImport } from './routes/_app/my-templates/$customTemplateId'
import { Route as AppMyTemplatesNewRouteImport } from './routes/_app/my-templates/new'
import { Route as AppResumesResumeIdRouteImport } from './routes/_app/resumes/$resumeId'
import { Route as AppResumesNewRouteImport } from './routes/_app/resumes/new'
import { Route as SiteDocsIndexRouteImport } from './routes/_site/docs/index'
import { Route as SiteDocsSlugRouteImport } from './routes/_site/docs/$slug'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app/admin/users/index'
import { Route as AppAdminUsersUserIdRouteImport } from './routes/_app/admin/users/$userId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameIndexRoute = UsernameIndexRouteImport.update({
  id: '/$username/',
  path: '/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameSlugRoute = UsernameSlugRouteImport.update({
  id: '/$username/$slug',
  path: '/$username/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAtsRoute = AppAtsRouteImport.update({
  id: '/ats',
  path: '/ats',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAtsCheckerRoute = SiteAtsCheckerRouteImport.update({
  id: '/ats-checker',
  path: '/ats-checker',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDocsRouteRoute = SiteDocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => SiteRoute,
} as any)
const SitePricingRoute = SitePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTemplatesRoute = SiteTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminAiRoute = AppAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminContentRoute = AppAdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminRevenueRoute = AppAdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminSystemRoute = AppAdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminTrafficRoute = AppAdminTrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppMyTemplatesIndexRoute = AppMyTemplatesIndexRouteImport.update({
  id: '/my-templates/',
  path: '/my-templates/',
  getParentRoute: () => AppRoute,
} as any)
const AppMyTemplatesCustomTemplateIdRoute =
  AppMyTemplatesCustomTemplateIdRouteImport.update({
    id: '/my-templates/$customTemplateId',
    path: '/my-templates/$customTemplateId',
    getParentRoute: () => AppRoute,
  } as any)
const AppMyTemplatesNewRoute = AppMyTemplatesNewRouteImport.update({
  id: '/my-templates/new',
  path: '/my-templates/new',
  getParentRoute: () => AppRoute,
} as any)
const AppResumesResumeIdRoute = AppResumesResumeIdRouteImport.update({
  id: '/resumes/$resumeId',
  path: '/resumes/$resumeId',
  getParentRoute: () => AppRoute,
} as any)
const AppResumesNewRoute = AppResumesNewRouteImport.update({
  id: '/resumes/new',
  path: '/resumes/new',
  getParentRoute: () => AppRoute,
} as any)
const SiteDocsIndexRoute = SiteDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteDocsRouteRoute,
} as any)
const SiteDocsSlugRoute = SiteDocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SiteDocsRouteRoute,
} as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminUsersUserIdRoute = AppAdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteRouteWithChildren
  '/docs': typeof SiteDocsRouteRouteWithChildren
  '/$username/$slug': typeof UsernameSlugRoute
  '/analytics': typeof AppAnalyticsRoute
  '/ats': typeof AppAtsRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/jobs': typeof AppJobsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/workspace': typeof AppWorkspaceRoute
  '/ats-checker': typeof SiteAtsCheckerRoute
  '/pricing': typeof SitePricingRoute
  '/privacy': typeof SitePrivacyRoute
  '/templates': typeof SiteTemplatesRoute
  '/terms': typeof SiteTermsRoute
  '/$username/': typeof UsernameIndexRoute
  '/admin/ai': typeof AppAdminAiRoute
  '/admin/content': typeof AppAdminContentRoute
  '/admin/revenue': typeof AppAdminRevenueRoute
  '/admin/system': typeof AppAdminSystemRoute
  '/admin/traffic': typeof AppAdminTrafficRoute
  '/my-templates/$customTemplateId': typeof AppMyTemplatesCustomTemplateIdRoute
  '/my-templates/new': typeof AppMyTemplatesNewRoute
  '/resumes/$resumeId': typeof AppResumesResumeIdRoute
  '/resumes/new': typeof AppResumesNewRoute
  '/docs/$slug': typeof SiteDocsSlugRoute
  '/admin/': typeof AppAdminIndexRoute
  '/my-templates/': typeof AppMyTemplatesIndexRoute
  '/docs/': typeof SiteDocsIndexRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/admin/users/': typeof AppAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/login': typeof LoginRoute
  '/$username/$slug': typeof UsernameSlugRoute
  '/analytics': typeof AppAnalyticsRoute
  '/ats': typeof AppAtsRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/jobs': typeof AppJobsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/workspace': typeof AppWorkspaceRoute
  '/ats-checker': typeof SiteAtsCheckerRoute
  '/pricing': typeof SitePricingRoute
  '/privacy': typeof SitePrivacyRoute
  '/templates': typeof SiteTemplatesRoute
  '/terms': typeof SiteTermsRoute
  '/$username': typeof UsernameIndexRoute
  '/admin/ai': typeof AppAdminAiRoute
  '/admin/content': typeof AppAdminContentRoute
  '/admin/revenue': typeof AppAdminRevenueRoute
  '/admin/system': typeof AppAdminSystemRoute
  '/admin/traffic': typeof AppAdminTrafficRoute
  '/my-templates/$customTemplateId': typeof AppMyTemplatesCustomTemplateIdRoute
  '/my-templates/new': typeof AppMyTemplatesNewRoute
  '/resumes/$resumeId': typeof AppResumesResumeIdRoute
  '/resumes/new': typeof AppResumesNewRoute
  '/docs/$slug': typeof SiteDocsSlugRoute
  '/admin': typeof AppAdminIndexRoute
  '/my-templates': typeof AppMyTemplatesIndexRoute
  '/docs': typeof SiteDocsIndexRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRouteRouteWithChildren
  '/_site/docs': typeof SiteDocsRouteRouteWithChildren
  '/$username/$slug': typeof UsernameSlugRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/ats': typeof AppAtsRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/workspace': typeof AppWorkspaceRoute
  '/_site/ats-checker': typeof SiteAtsCheckerRoute
  '/_site/pricing': typeof SitePricingRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/templates': typeof SiteTemplatesRoute
  '/_site/terms': typeof SiteTermsRoute
  '/$username/': typeof UsernameIndexRoute
  '/_site/': typeof SiteIndexRoute
  '/_app/admin/ai': typeof AppAdminAiRoute
  '/_app/admin/content': typeof AppAdminContentRoute
  '/_app/admin/revenue': typeof AppAdminRevenueRoute
  '/_app/admin/system': typeof AppAdminSystemRoute
  '/_app/admin/traffic': typeof AppAdminTrafficRoute
  '/_app/my-templates/$customTemplateId': typeof AppMyTemplatesCustomTemplateIdRoute
  '/_app/my-templates/new': typeof AppMyTemplatesNewRoute
  '/_app/resumes/$resumeId': typeof AppResumesResumeIdRoute
  '/_app/resumes/new': typeof AppResumesNewRoute
  '/_site/docs/$slug': typeof SiteDocsSlugRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/my-templates/': typeof AppMyTemplatesIndexRoute
  '/_site/docs/': typeof SiteDocsIndexRoute
  '/_app/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/docs'
    | '/$username/$slug'
    | '/analytics'
    | '/ats'
    | '/billing'
    | '/dashboard'
    | '/jobs'
    | '/profile'
    | '/settings'
    | '/workspace'
    | '/ats-checker'
    | '/pricing'
    | '/privacy'
    | '/templates'
    | '/terms'
    | '/$username/'
    | '/admin/ai'
    | '/admin/content'
    | '/admin/revenue'
    | '/admin/system'
    | '/admin/traffic'
    | '/my-templates/$customTemplateId'
    | '/my-templates/new'
    | '/resumes/$resumeId'
    | '/resumes/new'
    | '/docs/$slug'
    | '/admin/'
    | '/my-templates/'
    | '/docs/'
    | '/admin/users/$userId'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/$username/$slug'
    | '/analytics'
    | '/ats'
    | '/billing'
    | '/dashboard'
    | '/jobs'
    | '/profile'
    | '/settings'
    | '/workspace'
    | '/ats-checker'
    | '/pricing'
    | '/privacy'
    | '/templates'
    | '/terms'
    | '/$username'
    | '/admin/ai'
    | '/admin/content'
    | '/admin/revenue'
    | '/admin/system'
    | '/admin/traffic'
    | '/my-templates/$customTemplateId'
    | '/my-templates/new'
    | '/resumes/$resumeId'
    | '/resumes/new'
    | '/docs/$slug'
    | '/admin'
    | '/my-templates'
    | '/docs'
    | '/admin/users/$userId'
    | '/admin/users'
  id:
    | '__root__'
    | '/_app'
    | '/_site'
    | '/login'
    | '/_app/admin'
    | '/_site/docs'
    | '/$username/$slug'
    | '/_app/analytics'
    | '/_app/ats'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/_app/jobs'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/workspace'
    | '/_site/ats-checker'
    | '/_site/pricing'
    | '/_site/privacy'
    | '/_site/templates'
    | '/_site/terms'
    | '/$username/'
    | '/_site/'
    | '/_app/admin/ai'
    | '/_app/admin/content'
    | '/_app/admin/revenue'
    | '/_app/admin/system'
    | '/_app/admin/traffic'
    | '/_app/my-templates/$customTemplateId'
    | '/_app/my-templates/new'
    | '/_app/resumes/$resumeId'
    | '/_app/resumes/new'
    | '/_site/docs/$slug'
    | '/_app/admin/'
    | '/_app/my-templates/'
    | '/_site/docs/'
    | '/_app/admin/users/$userId'
    | '/_app/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  LoginRoute: typeof LoginRoute
  UsernameSlugRoute: typeof UsernameSlugRoute
  UsernameIndexRoute: typeof UsernameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/': {
      id: '/$username/'
      path: '/$username'
      fullPath: '/$username/'
      preLoaderRoute: typeof UsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$slug': {
      id: '/$username/$slug'
      path: '/$username/$slug'
      fullPath: '/$username/$slug'
      preLoaderRoute: typeof UsernameSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ats': {
      id: '/_app/ats'
      path: '/ats'
      fullPath: '/ats'
      preLoaderRoute: typeof AppAtsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace': {
      id: '/_app/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/ats-checker': {
      id: '/_site/ats-checker'
      path: '/ats-checker'
      fullPath: '/ats-checker'
      preLoaderRoute: typeof SiteAtsCheckerRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/docs': {
      id: '/_site/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof SiteDocsRouteRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/pricing': {
      id: '/_site/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof SitePricingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/templates': {
      id: '/_site/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof SiteTemplatesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/ai': {
      id: '/_app/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AppAdminAiRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/content': {
      id: '/_app/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AppAdminContentRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/revenue': {
      id: '/_app/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AppAdminRevenueRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/system': {
      id: '/_app/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AppAdminSystemRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/traffic': {
      id: '/_app/admin/traffic'
      path: '/traffic'
      fullPath: '/admin/traffic'
      preLoaderRoute: typeof AppAdminTrafficRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/my-templates/': {
      id: '/_app/my-templates/'
      path: '/my-templates'
      fullPath: '/my-templates/'
      preLoaderRoute: typeof AppMyTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-templates/$customTemplateId': {
      id: '/_app/my-templates/$customTemplateId'
      path: '/my-templates/$customTemplateId'
      fullPath: '/my-templates/$customTemplateId'
      preLoaderRoute: typeof AppMyTemplatesCustomTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-templates/new': {
      id: '/_app/my-templates/new'
      path: '/my-templates/new'
      fullPath: '/my-templates/new'
      preLoaderRoute: typeof AppMyTemplatesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resumes/$resumeId': {
      id: '/_app/resumes/$resumeId'
      path: '/resumes/$resumeId'
      fullPath: '/resumes/$resumeId'
      preLoaderRoute: typeof AppResumesResumeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resumes/new': {
      id: '/_app/resumes/new'
      path: '/resumes/new'
      fullPath: '/resumes/new'
      preLoaderRoute: typeof AppResumesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_site/docs/': {
      id: '/_site/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof SiteDocsIndexRouteImport
      parentRoute: typeof SiteDocsRouteRoute
    }
    '/_site/docs/$slug': {
      id: '/_site/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof SiteDocsSlugRouteImport
      parentRoute: typeof SiteDocsRouteRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/users/$userId': {
      id: '/_app/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AppAdminUsersUserIdRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminAiRoute: typeof AppAdminAiRoute
  AppAdminContentRoute: typeof AppAdminContentRoute
  AppAdminRevenueRoute: typeof AppAdminRevenueRoute
  AppAdminSystemRoute: typeof AppAdminSystemRoute
  AppAdminTrafficRoute: typeof AppAdminTrafficRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminUsersUserIdRoute: typeof AppAdminUsersUserIdRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminAiRoute: AppAdminAiRoute,
  AppAdminContentRoute: AppAdminContentRoute,
  AppAdminRevenueRoute: AppAdminRevenueRoute,
  AppAdminSystemRoute: AppAdminSystemRoute,
  AppAdminTrafficRoute: AppAdminTrafficRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminUsersUserIdRoute: AppAdminUsersUserIdRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAtsRoute: typeof AppAtsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppJobsRoute: typeof AppJobsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorkspaceRoute: typeof AppWorkspaceRoute
  AppMyTemplatesCustomTemplateIdRoute: typeof AppMyTemplatesCustomTemplateIdRoute
  AppMyTemplatesNewRoute: typeof AppMyTemplatesNewRoute
  AppResumesResumeIdRoute: typeof AppResumesResumeIdRoute
  AppResumesNewRoute: typeof AppResumesNewRoute
  AppMyTemplatesIndexRoute: typeof AppMyTemplatesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAtsRoute: AppAtsRoute,
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppJobsRoute: AppJobsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWorkspaceRoute: AppWorkspaceRoute,
  AppMyTemplatesCustomTemplateIdRoute: AppMyTemplatesCustomTemplateIdRoute,
  AppMyTemplatesNewRoute: AppMyTemplatesNewRoute,
  AppResumesResumeIdRoute: AppResumesResumeIdRoute,
  AppResumesNewRoute: AppResumesNewRoute,
  AppMyTemplatesIndexRoute: AppMyTemplatesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SiteDocsRouteRouteChildren {
  SiteDocsSlugRoute: typeof SiteDocsSlugRoute
  SiteDocsIndexRoute: typeof SiteDocsIndexRoute
}

const SiteDocsRouteRouteChildren: SiteDocsRouteRouteChildren = {
  SiteDocsSlugRoute: SiteDocsSlugRoute,
  SiteDocsIndexRoute: SiteDocsIndexRoute,
}

const SiteDocsRouteRouteWithChildren = SiteDocsRouteRoute._addFileChildren(
  SiteDocsRouteRouteChildren,
)

interface SiteRouteChildren {
  SiteDocsRouteRoute: typeof SiteDocsRouteRouteWithChildren
  SiteAtsCheckerRoute: typeof SiteAtsCheckerRoute
  SitePricingRoute: typeof SitePricingRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteTemplatesRoute: typeof SiteTemplatesRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteDocsRouteRoute: SiteDocsRouteRouteWithChildren,
  SiteAtsCheckerRoute: SiteAtsCheckerRoute,
  SitePricingRoute: SitePricingRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteTemplatesRoute: SiteTemplatesRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  LoginRoute: LoginRoute,
  UsernameSlugRoute: UsernameSlugRoute,
  UsernameIndexRoute: UsernameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
